### ISSUE TITLE
Can I run app on mobile chrome browser?

### ISSUE THREAD

**Issue by WebScaffolder** [okhiroyuki/nodejs-mobile-cordova#12]
Hi,

Can I run app on mobile chrome browser? Lets say localhost:8081 if I type on chrome?

**Comment by okhiroyuki** [comment]
@WebScaffolder 

Thank you for contacting us.
Unfortunately, it is not available in your browser.

**Comment by WebScaffolder** [comment]
dur mia
Jamial Hasan

 
 
 

    On Saturday, 19 August 2023 at 04:24:45 BST, Hiroyuki Okada ***@***.***> wrote:  
 
 


@WebScaffolder

Thank you for contacting us.
Unfortunately, it is not available in your browser.
